AWSTemplateFormatVersion: "2010-09-09"
Description: "Application server"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - development
      - test
      - staging
      - production
  MasterDBUsername:
    NoEcho: "true"
    Description: "Master Username"
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."
  MasterDBPassword:
    NoEcho: "true"
    Description: "Master Password"
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "must contain only alphanumeric characters."
Resources:
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2
      DBName: MyDatabase
      Engine: MySQL
      EngineVersion: "8.0.19"
      MultiAZ: True
      MasterUsername: !Ref MasterDBUsername
      MasterUserPassword: !Ref MasterDBPassword