AWSTemplateFormatVersion: "2010-09-09"
Description: "Web server"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - development
      - test
      - staging
      - production
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for web servers"
      VpcId:
        Fn::ImportValue:
          !Sub "${Environment}-VPC"
        SecurityGroupIngress:
          - SourceSecurityGroupId:
              Fn::ImportValue:
                !Sub "${Environment}-LoadBalancerSecurityGroup"
            FromPort: 80
            ToPort: 80
            IpProtocol: tcp
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-032598fcc7e9d1c7a # Amazon Linux 2 AMI
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: |
          yum update -y
          yum install httpd -y
          echo "<html><body><h1>test web server</h1></body></html>" > /var/www/html/index.html
          systemctl enable httpd
          systemctl start httpd